name: Test · docker.yml

on:
  workflow_dispatch:
  push:
    branches: [ci-test-1]

permissions:
  contents: read
  packages: write

jobs:
  call:
    uses: ./.github/workflows/docker.yml
    secrets: inherit
    with:
      image-tag: "test-0.0.1"
      image-repository: "bharathkumarradha/github-tests-app"
