name: Test · release.yml

on:
  workflow_dispatch:
  push:
    branches: [ci-test-1]

permissions:
  contents: write
  packages: write
  actions: read

jobs:
  call:
    uses: ./.github/workflows/release.yml
    secrets: inherit
    with:
      tag: "v0.0.1-test"
      notify: false
