name: Test · secret-scanning.yml

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  call:
    uses: ./.github/workflows/secret-scanning.yml
    secrets: inherit
    with:
      full-history: true
