name: Test · scan.yml (image)

on:
  workflow_dispatch:
  push:
    branches: [ci-test-1]

permissions:
  contents: read
  checks: write

jobs:
  call:
    uses: ./.github/workflows/scan.yml
    secrets: inherit
    with:
      scan-type: image
      image-ref: "docker.io/bharathkumarradha/github-tests-app@sha256:29a1a5ba0e74bab4b75a6366eb4c808d40f9cb1a0a7ac6985aaf2c7b5448a892"
