name: Test · chart.yml

on:
  workflow_dispatch:
  push:
    branches: [ci-test-1]

permissions:
  contents: read
  packages: write

jobs:
  call:
    uses: ./.github/workflows/chart.yml
    secrets: inherit
    with:
      chart-name: "github-tests-app"
      chart-version: "0.1.0"
      chart-app-version: "0.1.0"
      chart-repository: "bharathkumarradha"
      check-docs: false
